# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Dell', max_length=20)),
                ('screen_size', models.FloatField(default=11)),
                ('processor_type', models.CharField(default='Inspiron 11', max_length=20)),
                ('price', models.CharField(default='30000 руб', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(unique=True)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_surname', models.CharField(max_length=20)),
                ('user_thirdname', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_adress', models.CharField(max_length=50)),
            ],
        ),
    ]
