# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_lab6', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='computer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_lab6.ComputerModel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='order_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_lab6.OrderModel'),
        ),
    ]
